set path=%~dp0..\h\comp\mingw\bin;%~dp0bin\win\mingw;%path%
set path=%~dp0;%~dp0..\tools;%~dp0..\ads101\acesdk;%~dp0..\MySQL\LIB;%~dp0..\Firebird;%path%
set HB_WITH_MYSQL=%~dp0..\MySQL\include
set HB_WITH_ADS=%~dp0..\ads101\acesdk
set HB_WITH_FIREBIRD=%~dp0..\Firebird\include
set HB_WITH_CURL=%~dp0..\h\comp\mingw\include
set HB_WITH_OPENSSL=%~dp0..\h\comp\mingw\include
set HB_WITH_MINIZIP=%~dp0..\h\comp\mingw\include
set HB_WITH_FREEIMAGE=%~dp0..\FreeImage\Dist
rem set HB_BUILD_DEBUG=yes
rem set HB_MT=yes